### PR TITLE
core: Implement PVR register

### PR DESCRIPTION
**Pull request by iamjpn**
Microwatt has been allocated a PVR version of 0x0063. Implement a PVR
with this value.

Signed-off-by: Jordan Niethe <jniethe5@gmail.com>

### CODE REVIEW

**Comment by mikey** [comment]
Holding off on merging this until we have test case and privilege checks. See #221 for discussion.

**Comment by iamjpn** [comment]
I've now added test cases for supervisor and problem state. As Paul pointed out the privilege checking is already handled.

**Comment by paulusmack** [comment]
This mostly looks good now. The one minor comment I have is that in the misc test you do a mfspr %r3,PVR without establishing any definite value in %r3 first. Since the behaviour of mfspr in privileged mode to an unimplemented SPR is to act as a no-op, that is, to leave the destination register unchanged, you need to set %r3 to some definite value that is not 0x630000 before doing the mfspr. Otherwise there is the possibility that %r3 might contain 0x630000 before the mfspr, and the test would succeed even if the PVR was not implemented. I suggest just using %r3 rather than %r4 in the preceding instructions, so we know %r3 contains 0xdeadbeef at the point of the mfspr.

**Comment by mikey** [comment]
@iamjpn you'll also need to run tests/update_console_tests to update the misc test binaries and console output.

**Comment by iamjpn** [comment]
> This mostly looks good now. The one minor comment I have is that in the misc test you do a mfspr %r3,PVR without establishing any definite value in %r3 first. Since the behaviour of mfspr in privileged mode to an unimplemented SPR is to act as a no-op, that is, to leave the destination register unchanged, you need to set %r3 to some definite value that is not 0x630000 before doing the mfspr. 
Good point.
>Otherwise there is the possibility that %r3 might contain 0x630000 before the mfspr, and the test would succeed even if the PVR was not implemented. I suggest just using %r3 rather than %r4 in the preceding instructions, so we know %r3 contains 0xdeadbeef at the point of the mfspr.
I think I will also add another test that first just tests mfspr by itself.

**Comment by mikey** [comment]
Thanks @iamjpn

**Pull request merged**
