### PR TITLE
Add support for prefixed instructions

### PR DESCRIPTION
**Pull request by paulusmack**
It turns out that if you are not implementing vector or VSX, there are less than 20 prefixed instructions in v3.1B, namely pnop plus a bunch of extended D-form loads and stores. So this adds support for them, since it turned out to be less work than expected.

Prefixed instructions are handled by having decode1 recognize and swallow the prefix, and then modify the insn_code for the next instruction that comes along; for example, INSN_lfs gets changed to INSN_plfs. There are then entries for the various prefixed instructions in the decode table. There is also a new form of alignment interrupt to generate if the address of the prefix mod 64 is equal to 60, and a bit in SRR1 to indicate that various interrupts occurred due to a prefixed instruction.

There is a test program here that does some basic testing, but more tests could be added.

The first commit, which modifies fetch1, is not really related, but is a useful conceptual cleanup. It could be put into a separate pull request if necessary.

### CODE REVIEW

**Comment by paulusmack** [comment]
> Cool. Does it boot a pcrel Linux?

I haven't tried, but I'll give it a go this weekend. What config option(s) would I need to turn on?

I have tried compiling coremark with -mcpu=power10, and to make that work I had to implement the set[n]bc[r] instructions. Compiled that way it runs faster than with -mcpu=power9 by a bit less than 1%.

**Comment by mikey** [comment]
@paulusmack Sorry I've not had time to look at this but I'm happy if you want to pull this in yourself.

**Comment by npiggin** [comment]
You want CONFIG_PPC_KERNEL_PCREL=y which can be selected if you select POWER10 CPU target.

**Comment by paulusmack** [comment]
> Cool. Does it boot a pcrel Linux?

Yes, with the two extra commits I just pushed, which implement the setbc* and br[hwd] instructions.

**Comment by npiggin** [comment]
Great. I wonder how far off you are from calling it v3.1 support.

cfuged, cntlzdm, cnttzdm,  pextd, pdepd seem to be needed AFAIKS. hashchk and hashst too although you could implement them with noops to start with.

**Comment by paulusmack** [comment]
> Great. I wonder how far off you are from calling it v3.1 support.

Pretty close, I reckon. Strictly speaking I guess we need things like the two data watchpoints as well.

> cfuged, cntlzdm, cnttzdm, pextd, pdepd seem to be needed AFAIKS. hashchk and hashst too although you could implement them with noops to start with.

I thought I had read that hash* was optional but now I can't find any statement to that effect. As you say, they could be noops.

**Pull request merged**
