### PR TITLE
Add files for openocd v0.11

### PR DESCRIPTION
**Pull request by shenki**
The protocol used by the spi bridge firmware changed as of openocd
v0.11. As this is the version packaged by Debian Bullseye, add the
firmware for convince.

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by shenki** [comment]
Can someone who has the old opencd please test to make sure I didn't break it?

**Comment by paulusmack** [comment]
> Can someone who has the old opencd please test to make sure I didn't break it?

I tried with openocd-0.10.0 (packaged in Fedora 32) and got this:

paulus@thinks microwatt-fusesoc]$ ~/microwatt/openocd/flash-arty -f a100 build/microwatt_0/arty_a7-100-vivado/microwatt_0.bit
init; jtagspi_init 0 {/home/paulus/microwatt/openocd/bscan_spi_xc7a100t.bit}; ; jtagspi_program {build/microwatt_0/arty_a7-100-vivado/microwatt_0.bit} 0x0 ; fpga_program; exit
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 25000 kHz
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
fpga_program
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 25000 kHz
Info : JTAG tap: xc7.tap tap/device found: 0x13631093 (mfg: 0x049 (Xilinx), part: 0x3631, ver: 0x1)
loaded file /home/paulus/microwatt/openocd/bscan_spi_xc7a100t.bit to pld device 0 in 0s 213018us
Info : JTAG tap: xc7.tap tap/device found: 0x13631093 (mfg: 0x049 (Xilinx), part: 0x3631, ver: 0x1)
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
flash 'jtagspi' found at 0x00000000
auto erase enabled
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
Info : sector 0 took 1896 ms
Info : sector 1 took 1915 ms
Info : sector 2 took 105 ms
Info : sector 3 took 120 ms
Info : sector 4 took 102 ms
Info : sector 5 took 101 ms
Info : sector 6 took 102 ms
Info : sector 7 took 101 ms
Info : sector 8 took 112 ms
Info : sector 9 took 109 ms
Info : sector 10 took 106 ms
Info : sector 11 took 99 ms
Info : sector 12 took 108 ms
Info : sector 13 took 111 ms
Info : sector 14 took 106 ms
Info : sector 15 took 101 ms
Info : sector 16 took 114 ms
Info : sector 17 took 105 ms
Info : sector 18 took 103 ms
Info : sector 19 took 110 ms
Info : sector 20 took 105 ms
Info : sector 21 took 106 ms
Info : sector 22 took 103 ms
Info : sector 23 took 102 ms
Info : sector 24 took 102 ms
Info : sector 25 took 112 ms
Info : sector 26 took 103 ms
Info : sector 27 took 103 ms
Info : sector 28 took 111 ms
Info : sector 29 took 103 ms
Info : sector 30 took 105 ms
Info : sector 31 took 106 ms
Info : sector 32 took 103 ms
Info : sector 33 took 110 ms
Info : sector 34 took 111 ms
Info : sector 35 took 108 ms
Info : sector 36 took 101 ms
wrote 2424832 bytes from file build/microwatt_0/arty_a7-100-vivado/microwatt_0.bit in 23.614477s (100.277 KiB/s)
/home/paulus/microwatt/openocd/xilinx-xc7.cfg:54: Error: invalid subcommand "verify_image build/microwatt_0/arty_a7-100-vivado/microwatt_0.bit 0x0"
in procedure 'jtagspi_program' 
in procedure 'flash' called at file "/home/paulus/microwatt/openocd/xilinx-xc7.cfg", line 54

I think it has actually programmed the flash OK, but it didn't reset/reload the FPGA.

**Comment by paulusmack** [comment]
With this I get the following error:

  File "/home/paulus/microwatt/openocd/flash-arty", line 53
    flash(config, proxy, args.address, args.file, args.filetype.lower())
    ^
SyntaxError: invalid syntax

This is on a machine where openocd is at version 0.11.

**Comment by shenki** [comment]
On Tue, 11 May 2021 at 07:43, Paul Mackerras ***@***.***> wrote:
>
> With this I get the following error:
>
> File "/home/paulus/microwatt/openocd/flash-arty", line 53
> flash(config, proxy, args.address, args.file, args.filetype.lower())
> ^
> SyntaxError: invalid syntax

Fixed now.

**Pull request merged**
