### PR TITLE
MSR fixes, implement privilege checking, implement dcbz

### PR DESCRIPTION
**Pull request by paulusmack**

### CODE REVIEW

**Comment by paulusmack** [comment]
Pushed an update - I missed adding some files in the commit that adds the privileged instruction test.

**Comment by paulusmack** [comment]
... and this time let's have PASS in test_privileged.console_out not FAIL...

**Comment by paulusmack** [comment]
and also let's fix a typo in Makefile

**Comment by antonblanchard** [comment]
Thanks @paulusmack!

**Pull request merged**
