### PR TITLE
Fix ld error in elf maketarget

### PR DESCRIPTION
**Pull request by shingarov**
Signed-off-by: Boris Shingarov <shingarov@labware.com>

### CODE REVIEW

**Comment by ozbenh** [comment]
Please provide a more details comment, including the error that is fixed (hint: worked for me :-)

**Comment by shingarov** [comment]
I just pushed an amended commit message.

> hint: worked for me

I am surprised.  How is it possible that when you call the linker like this,
```
ld -T linkscript.lds A.o B.o C.o linkscript.lds
```
that it's not complaining about `linker script appears multiple times`, this seems impossible to me.  Wait, how is your ld configured? i.e. what does
```
powerpc64le-linux-gnu-ld -v
```
say?

**Comment by ozbenh** [comment]
$ powerpc64le-linux-gnu-ld -v
GNU ld (GNU Binutils for Ubuntu) 2.30

**Comment by shingarov** [comment]
Mine's 2.34.  Hang on, let me see what will happen when I roll back to 2.30...

**Comment by shingarov** [comment]
Oh, I see.  As of commit 82d7a6f4e3c on 2019-05-23 GNU ld is more strict:
https://www.mail-archive.com/bug-binutils@gnu.org/msg30975.html

**Comment by shingarov** [comment]
Anything else needed form me before this can be merged?

**Comment by mikey** [comment]
Thanks @shingarov

**Pull request merged**
