### PR TITLE
Interrupts for GPIO

### PR DESCRIPTION
**Pull request by mkj**
This adds interrupts for GPIO lines. I've kept the register interface as bit-per-line split across 3 "trigger type" registers (rising/falling/level etc), though the other option would be to have perhaps one register per line taking a type value. Any suggested changes welcome - it probably needs a bit of tidying before merging.

This pull request also hooks up the GPIOs on the arty board for testing purposes.

I have a Linux driver in https://github.com/CodeConstruct/linux/commit/46348b505100d52eb197eb66750e6a72ceb1f20b based on @shenki 's https://github.com/shenki/linux/tree/microwatt-v5.16

### CODE REVIEW

**Comment by mkj** [comment]
I've pushed an update with an extra FF for the interrupt edge detection, and no longer latching the input value on interrupt.
This is rebased to current master.

**Comment by paulusmack** [comment]
What model if any did you follow in deciding what registers to put at what offsets?

So far we have been using drivers/gpio/gpio-ftgpio010.c in the Linux kernel without needing to modify it. It doesn't look to me like the offsets and semantics of your new registers match up with what that driver expects.

If you have followed the model of some other driver, and we can just use that driver as is, then tell us which driver that is. Otherwise I suggest you follow the layout that gpio-ftgpio010.c is expecting so that we don't need to modify it. There doesn't seem to be any point to pushing changes upstream in Linux just because we have arbitrarily used a different register layout.,

**Comment by mkj** [comment]
The register offsets are fairly arbitrary. I didn't realise it was based on gpio-ftgpio010.c, I'll update it to match.

**Comment by mkj** [comment]
I've updated the register interface to work as `compatible = "faraday,ftgpio010"`. 
It looks like the failing verilator github action is spurious - it works here and seems unrelated.

**Pull request merged**
