### PR TITLE
Decode in block RAM and other improvements

### PR DESCRIPTION
**Pull request by paulusmack**
Overall, on the Arty A7-100, LUT usage is down by 784 LUTs and timing is better. Block RAM tile usage is up by 3. In fact we can now fit in the FPU as well as the litedram and liteeth controllers in the arty_a7-35 target (though sadly not litesdcard as well). Coremark performance is up to 205 (about 2% better) without the HAS_SHORT_MULT option.

On the downside, 64-bit integer multiplications will be a few cycles slower, and our icache miss latency is increased by one cycle.

We now have as standard a 33-bit signed integer multiplier with one cycle latency in the execute unit, which does 32-bit signed and unsigned multiply instructions. 64-bit multiplies are now done in the FPU if you have an FPU. So where we previously had two 64-bit multipliers (plus an optional 16-bit multiplier), we now have a 64-bit multiplier in the FPU and a 33-bit multiplier in execute1.

The other big thing here is that the instruction decode table in decode1 is now indexed by a 9-bit insn_code (instruction code) which is computed in a predecode step that occurs when filling an icache line.  The predecode step takes one cycle and does two instructions in parallel. The icache RAM is now 72 bits wide, i.e. 2 instructions at 36 bits each. For valid instructions we store the bottom 26 bits of the instruction word plus the 9-bit insn_code; we drop the primary opcode in order not to increase BRAM usage. The primary opcode could be obtained from the insn_code if necessary. For invalid (illegal) instructions we store the whole 32-bit instruction word. The MSB of the 36 bits is 1 for an invalid instruction or 0 for a valid instruction. The insn_code uniquely identifies the instruction down to the level of Rc/OE variants, i.e. add, add., addo and addo. all have the same insn_code, but a different code from subf, addi, addc, etc.

There are also some minor cleaups and some restructuring of the FPU logic that were motivated by wanting to do microprogrammed control of the FPU but turned out to decrease LUT usage and improve timing and so were included here.

### CODE REVIEW

**Comment by paulusmack** [comment]
Hmmm, it seems that this doesn't run correctly on the ECP5 as of the "Pre-decode instructions when writing them to icache" commit. Investigating...

**Comment by paulusmack** [comment]
It now works on ECP5.

**Comment by paulusmack** [comment]
Rebased on top of recent changes, plus I eliminated most of the extra latency of doing integer multiplication in the FPU (except for one cycle for Rc=1 forms). On the downside it no longer fits in the A7-35 with the FPU.

**Comment by paulusmack** [comment]
And now I took out the "Do 64-bit integer multiplication instructions in the FPU" since it doesn't seem to be helping reduce LUT utilization any more.

**Comment by mikey** [comment]
Thanks @paulusmack

**Pull request merged**
