### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by pragyabansal02**

### CODE REVIEW

**Comment by paulusmack** [comment]
Commit message is inadequate. It needs to say why this is a good change to make.

**Comment by mikey** [comment]
Please add a signed off by so the DCO test passes.

**Comment by mikey** [comment]
This doesn't seem to work. There is a bintohex in hello_world, but no bintodec so your Makefile change is not going to work.

**Comment by antonblanchard** [comment]
Closing, feel free to reopen when the comments from @paulusmack and @mikey are addressed.

**Pull request closed without merging**
