### PR TITLE
The gammar mistakes were corrected successfully

### PR DESCRIPTION
**Pull request by ads123ads**
Nothing is ever small.

### CODE REVIEW

**Comment by mikey** [comment]
Thanks, but please add a signed off by (this is what the DCO test is checking).

**Comment by paulusmack** [comment]
The commit description has a spelling mistake, and it should be expressed as an imperative.

**Comment by paulusmack** [comment]
Also, I dispute that either of the things changed here were incorrect.

**Comment by antonblanchard** [comment]
Agreed, closing

**Pull request closed without merging**
